#ifndef CONDITIONALS_H
#define CONDITIONALS_H

/*
 * This configuration file contains defines that depend on configuration but are not editable.
 *
 * - Serial comunication type
 * - Board type
 * - Mechanism type
 * - Thermistor type
 * - Temperature limits
 * - Extruders number
 * - UI Language
 *
 */
 
// Serial comunication
#if DISABLED(SERIAL_PORT)
  #error DEPENDENCY ERROR: Missing setting SERIAL_PORT
#endif
#if DISABLED(BAUDRATE)
  #error DEPENDENCY ERROR: Missing setting BAUDRATE
#endif
#if DISABLED(MACHINE_UUID)
	#error DEPENDENCY ERROR: Missing setting MACHINE_UUID
#endif

//board
#if DISABLED(MOTHERBOARD)
  #error DEPENDENCY ERROR: Missing setting MOTHERBOARD
#endif

//Mechanism
#if DISABLED(MEACHANISM)
  #error DEPENDENCY ERROR: Missing setting MECHANISM
#endif

//Power supply
#if DISABLED(POWER_SUPPLY)
  #error DEPENDENCY ERROR: Missing setting POWER_SUPPLY
#endif

//Thermistor
#if DISABLED(TEMP_SENSOR_0)
  #error DEPENDENCY ERROR: Missing setting TEMP_SENSOR_0
#endif
#if DISABLED(TEMP_SENSOR_1)
  #error DEPENDENCY ERROR: Missing setting TEMP_SENSOR_1
#endif
#if DISABLED(TEMP_SENSOR_2)
  #error DEPENDENCY ERROR: Missing setting TEMP_SENSOR_2
#endif
#if DISABLED(TEMP_SENSOR_3)
  #error DEPENDENCY ERROR: Missing setting TEMP_SENSOR_3
#endif
#if DISABLED(TEMP_SENSOR_BED)
  #error DEPENDENCY ERROR: Missing setting TEMP_SENSOR_BED
#endif
#if (THERMISTORHEATER_0 == 998) || (THERMISTORHEATER_1 == 998) || (THERMISTORHEATER_2 == 998) || (THERMISTORHEATER_3 == 998) || (THERMISTORBED == 998) //User defined table
  #if DISABLED(DUMMY_THERMISTOR_998_VALUE)
    #error DEPENDENCY ERROR: Missing setting DUMMY_THERMISTOR_998_VALUE
  #endif
#endif

//Temperature
/**
 * Temperature defines
 */
#if ENABLED(TEMP_RESIDENCY_TIME)
  #if DISABLED(TEMP_HYSTERESIS)
    #error DEPENDENCY ERROR: Missing setting TEMP_HYSTERESIS
  #endif
  #if DISABLED(TEMP_WINDOW)
    #error DEPENDENCY ERROR: Missing setting TEMP_WINDOW
  #endif
#endif
#if TEMP_SENSOR_0 != 0
  #if DISABLED(HEATER_0_MAXTEMP)
    #error DEPENDENCY ERROR: Missing setting HEATER_0_MAXTEMP
  #endif
  #if DISABLED(HEATER_0_MINTEMP)
    #error DEPENDENCY ERROR: Missing setting HEATER_0_MINTEMP
  #endif
#endif
#if TEMP_SENSOR_1 != 0
  #if DISABLED(HEATER_1_MAXTEMP)
    #error DEPENDENCY ERROR: Missing setting HEATER_1_MAXTEMP
  #endif
  #if DISABLED(HEATER_0_MINTEMP)
    #error DEPENDENCY ERROR: Missing setting HEATER_1_MINTEMP
  #endif
#endif
#if TEMP_SENSOR_2 != 0
  #if DISABLED(HEATER_2_MAXTEMP)
    #error DEPENDENCY ERROR: Missing setting HEATER_2_MAXTEMP
  #endif
  #if DISABLED(HEATER_0_MINTEMP)
    #error DEPENDENCY ERROR: Missing setting HEATER_2_MINTEMP
  #endif
#endif
#if TEMP_SENSOR_3 != 0
  #if DISABLED(HEATER_3_MAXTEMP)
    #error DEPENDENCY ERROR: Missing setting HEATER_3_MAXTEMP
  #endif
  #if DISABLED(HEATER_0_MINTEMP)
    #error DEPENDENCY ERROR: Missing setting HEATER_3_MINTEMP
  #endif
#endif
#if TEMP_SENSOR_BED != 0
  #if DISABLED(BED_MAXTEMP)
    #error DEPENDENCY ERROR: Missing setting BED_MAXTEMP
  #endif
  #if DISABLED(HEATER_0_MINTEMP)
    #error DEPENDENCY ERROR: Missing setting BED_MINTEMP
  #endif
#endif
#if DISABLED(PLA_PREHEAT_HOTEND_TEMP)
  #error DEPENDENCY ERROR: Missing setting PLA_PREHEAT_HOTEND_TEMP
#endif
#if DISABLED(PLA_PREHEAT_HPB_TEMP)
  #error DEPENDENCY ERROR: Missing setting PLA_PREHEAT_HPB_TEMP
#endif
#if DISABLED(PLA_PREHEAT_FAN_SPEED)
  #error DEPENDENCY ERROR: Missing setting PLA_PREHEAT_FAN_SPEED
#endif
#if DISABLED(ABS_PREHEAT_HOTEND_TEMP)
  #error DEPENDENCY ERROR: Missing setting ABS_PREHEAT_HOTEND_TEMP
#endif
#if DISABLED(ABS_PREHEAT_HPB_TEMP)
  #error DEPENDENCY ERROR: Missing setting ABS_PREHEAT_HPB_TEMP
#endif
#if DISABLED(ABS_PREHEAT_FAN_SPEED)
  #error DEPENDENCY ERROR: Missing setting ABS_PREHEAT_FAN_SPEED
#endif
#if DISABLED(GUM_PREHEAT_HOTEND_TEMP)
  #error DEPENDENCY ERROR: Missing setting GUM_PREHEAT_HOTEND_TEMP
#endif
#if DISABLED(GUM_PREHEAT_HPB_TEMP)
  #error DEPENDENCY ERROR: Missing setting GUM_PREHEAT_HPB_TEMP
#endif
#if DISABLED(GUM_PREHEAT_FAN_SPEED)
  #error DEPENDENCY ERROR: Missing setting GUM_PREHEAT_FAN_SPEED
#endif

//extruders
#if DISABLED(EXTRUDERS)
  #error DEPENDENCY ERROR: Missing setting EXTRUDERS
#endif
#if DISABLED(DRIVER_EXTRUDERS)
  #error DEPENDENCY ERROR: Missing setting DRIVER_EXTRUDERS
#endif

//Language
#if DISABLED(LANGUAGE_CHOICE)
  #error DEPENDENCY ERROR: Missing setting LANGUAGE_CHOICE
#endif

///FEATURE

//Temperature
#if DISABLED(PID_MAX)
  #error DEPENDENCY ERROR: Missing setting PID_MAX
#endif
#if DISABLED(MAX_BED_POWER)
  #error DEPENDENCY ERROR: Missing setting MAX_BED_POWER
#endif
#if ENABLED(PIDTEMP) || ENABLED(PIDTEMPBED)
  #if DISABLED(MAX_OVERSHOOT_PID_AUTOTUNE)
    #error DEPENDENCY ERROR: Missing setting MAX_OVERSHOOT_PID_AUTOTUNE
  #endif
#endif
#if ENABLED(PIDTEMP)
  #if DISABLED(PID_OPENLOOP)
    #error DEPENDENCY ERROR: Missing setting PID_FUNCTIONAL_RANGE
  #endif
  #if DISABLED(PID_INTEGRAL_DRIVE_MAX)
    #error DEPENDENCY ERROR: Missing setting PID_INTEGRAL_DRIVE_MAX
  #endif
  #if DISABLED(DEFAULT_Kp)
    #error DEPENDENCY ERROR: Missing setting DEFAULT_Kp
  #endif
  #if DISABLED(DEFAULT_Ki)
    #error DEPENDENCY ERROR: Missing setting DEFAULT_Ki
  #endif
  #if DISABLED(DEFAULT_Kd)
    #error DEPENDENCY ERROR: Missing setting DEFAULT_Kd
  #endif
#endif
#if ENABLED(PIDTEMPBED)
  #if DISABLED(PID_BED_INTEGRAL_DRIVE_MAX)
    #error DEPENDENCY ERROR: Missing setting PID_BED_INTEGRAL_DRIVE_MAX
  #endif
  #if DISABLED(DEFAULT_bedKp)
    #error DEPENDENCY ERROR: Missing setting DEFAULT_bedKp
  #endif
  #if DISABLED(DEFAULT_bedKi)
    #error DEPENDENCY ERROR: Missing setting DEFAULT_bedKi
  #endif
  #if DISABLED(DEFAULT_bedKd)
    #error DEPENDENCY ERROR: Missing setting DEFAULT_bedKd
  #endif
#endif
#if ENABLED(BED_LIMIT_SWITCHING)
  #if DISABLED(BED_HYSTERESIS)
    #error DEPENDENCY ERROR: Missing setting BED_HYSTERESIS
  #endif
  #if DISABLED(BED_CHECK_INTERVAL)
    #error DEPENDENCY ERROR: Missing setting BED_CHECK_INTERVAL
  #endif
#endif
#if ENABLED(THERMAL_PROTECTION_HOTENDS)
  #if DISABLED(THERMAL_PROTECTION_PERIOD)
    #error DEPENDENCY ERROR: Missing setting THERMAL_PROTECTION_PERIOD
  #endif
  #if DISABLED(THERMAL_PROTECTION_HYSTERESIS)
    #error DEPENDENCY ERROR: Missing setting THERMAL_PROTECTION_HYSTERESIS
  #endif
  #if DISABLED(WATCH_TEMP_PERIOD)
    #error DEPENDENCY ERROR: Missing setting WATCH_TEMP_PERIOD
  #endif
  #if DISABLED(WATCH_TEMP_INCREASE)
    #error DEPENDENCY ERROR: Missing setting WATCH_TEMP_INCREASE
  #endif
#endif
#if ENABLED(THERMAL_PROTECTION_BED)
  #if DISABLED(THERMAL_PROTECTION_BED_PERIOD)
    #error DEPENDENCY ERROR: Missing setting THERMAL_PROTECTION_BED_PERIOD
  #endif
  #if DISABLED(THERMAL_PROTECTION_BED_HYSTERESIS)
    #error DEPENDENCY ERROR: Missing setting THERMAL_PROTECTION_BED_HYSTERESIS
  #endif
#endif
//fan
#if DISABLED(SOFT_PWM_SCALE)
  #error DEPENDENCY ERROR: Missing setting SOFT_PWM_SCALE
#endif

#if ENABLED(CONTROLLERFAN)
  #if DISABLED(CONTROLLERFAN_SECS)
    #error DEPENDENCY ERROR: Missing setting CONTROLLERFAN_SECS
  #endif
  #if DISABLED(CONTROLLERFAN_SPEED)
    #error DEPENDENCY ERROR: Missing setting CONTROLLERFAN_SPEED
  #endif
  #if DISABLED(CONTROLLERFAN_MIN_SPEED)
    #error DEPENDENCY ERROR: Missing setting CONTROLLERFAN_MIN_SPEED
  #endif
#endif

#if ENABLED(EXTRUDER_AUTO_FAN)
  #if DISABLED(EXTRUDER_AUTO_FAN_TEMPERATURE)
    #error DEPENDENCY ERROR: Missing setting EXTRUDER_AUTO_FAN_TEMPERATURE
  #endif
  #if DISABLED(EXTRUDER_AUTO_FAN_SPEED)
    #error DEPENDENCY ERROR: Missing setting EXTRUDER_AUTO_FAN_SPEED
  #endif
  #if DISABLED(EXTRUDER_AUTO_FAN_MIN_SPEED)
    #error DEPENDENCY ERROR: Missing setting EXTRUDER_AUTO_FAN_MIN_SPEED
  #endif
#endif

//extruder
#if ENABLED(PREVENT_DANGEROUS_EXTRUDE)
  #if DISABLED(EXTRUDE_MINTEMP)
    #error DEPENDENCY ERROR: Missing setting EXTRUDE_MINTEMP
  #endif
  #if ENABLED(PREVENT_LENGTHY_EXTRUDE)
    #if DISABLED(EXTRUDE_MAXLENGTH)
      #error DEPENDENCY ERROR: Missing setting EXTRUDE_MAXLENGTH
    #endif
  #endif
#endif

#if ENABLED(NPR2)
  #if DISABLED(COLOR_STEP)
    #error DEPENDENCY ERROR: Missing setting COLOR_STEP
  #endif
  #if DISABLED(COLOR_SLOWRATE)
    #error DEPENDENCY ERROR: Missing setting COLOR_SLOWRATE
  #endif
  #if DISABLED(COLOR_HOMERATE)
    #error DEPENDENCY ERROR: Missing setting COLOR_HOMERATE
  #endif
  #if DISABLED(MOTOR_ANGLE)
    #error DEPENDENCY ERROR: Missing setting MOTOR_ANGLE
  #endif
  #if DISABLED(DRIVER_MICROSTEP)
    #error DEPENDENCY ERROR: Missing setting DRIVER_MICROSTEP
  #endif
  #if DISABLED(CARTER_MOLTIPLICATOR)
    #error DEPENDENCY ERROR: Missing setting CARTER_MOLTIPLICATOR
  #endif
#endif

#if ENABLED(IDLE_OOZING_PREVENT)
  #if DISABLED(IDLE_OOZING_MINTEMP)
    #error DEPENDENCY ERROR: Missing setting IDLE_OOZING_MINTEMP
  #endif
  #if DISABLED(IDLE_OOZING_FEEDRATE)
    #error DEPENDENCY ERROR: Missing setting IDLE_OOZING_FEEDRATE
  #endif
  #if DISABLED(IDLE_OOZING_SECONDS)
    #error DEPENDENCY ERROR: Missing setting IDLE_OOZING_SECONDS
  #endif
  #if DISABLED(IDLE_OOZING_LENGTH)
    #error DEPENDENCY ERROR: Missing setting IDLE_OOZING_LENGTH
  #endif
  #if DISABLED(IDLE_OOZING_RECOVER_LENGTH)
    #error DEPENDENCY ERROR: Missing setting IDLE_OOZING_RECOVER_LENGTH
  #endif
  #if DISABLED(IDLE_OOZING_RECOVER_FEEDRATE)
    #error DEPENDENCY ERROR: Missing setting IDLE_OOZING_RECOVER_FEEDRATE
  #endif
#endif

#if ENABLED(EXTRUDER_RUNOUT_PREVENT)
  #if DISABLED(EXTRUDER_RUNOUT_MINTEMP)
    #error DEPENDENCY ERROR: Missing setting EXTRUDER_RUNOUT_MINTEMP
  #endif
  #if DISABLED(EXTRUDER_RUNOUT_SECONDS)
    #error DEPENDENCY ERROR: Missing setting EXTRUDER_RUNOUT_SECONDS
  #endif
  #if DISABLED(EXTRUDER_RUNOUT_ESTEPS)
    #error DEPENDENCY ERROR: Missing setting EXTRUDER_RUNOUT_ESTEPS
  #endif
  #if DISABLED(EXTRUDER_RUNOUT_SPEED)
    #error DEPENDENCY ERROR: Missing setting EXTRUDER_RUNOUT_SPEED
  #endif
  #if DISABLED(EXTRUDER_RUNOUT_EXTRUDE)
    #error DEPENDENCY ERROR: Missing setting EXTRUDER_RUNOUT_EXTRUDE
  #endif
#endif

#if ENABLED(EASY_LOAD)
  #if DISABLED(BOWDEN_LENGTH)
    #error DEPENDENCY ERROR: Missing setting BOWDEN_LENGTH
  #endif
  #if DISABLED(LCD_PURGE_LENGTH)
    #error DEPENDENCY ERROR: Missing setting LCD_PURGE_LENGTH
  #endif
  #if DISABLED(LCD_RETRACT_LENGTH)
    #error DEPENDENCY ERROR: Missing setting LCD_RETRACT_LENGTH
  #endif
  #if DISABLED(LCD_PURGE_FEEDRATE)
    #error DEPENDENCY ERROR: Missing setting LCD_PURGE_FEEDRATE
  #endif
  #if DISABLED(LCD_RETRACT_FEEDRATE)
    #error DEPENDENCY ERROR: Missing setting LCD_RETRACT_FEEDRATE
  #endif
  #if DISABLED(LCD_LOAD_FEEDRATE)
    #error DEPENDENCY ERROR: Missing setting LCD_LOAD_FEEDRATE
  #endif
  #if DISABLED(LCD_UNLOAD_FEEDRATE)
    #error DEPENDENCY ERROR: Missing setting LCD_UNLOAD_FEEDRATE
  #endif
#endif

#if ENABLED(ADVANCE)
  #if DISABLED(EXTRUDER_ADVANCE_K)
    #error DEPENDENCY ERROR: Missing setting EXTRUDER_ADVANCE_K
  #endif
  #if DISABLED(D_FILAMENT)
    #error DEPENDENCY ERROR: Missing setting D_FILAMENT
  #endif
  #if DISABLED(STEPS_MM_E)
    #error DEPENDENCY ERROR: Missing setting STEPS_MM_E
  #endif
#endif

#if ENABLED(FILAMENTCHANGEENABLE)
  #if DISABLED(FILAMENTCHANGE_XPOS)
    #error DEPENDENCY ERROR: Missing setting FILAMENTCHANGE_XPOS
  #endif
  #if DISABLED(FILAMENTCHANGE_YPOS)
    #error DEPENDENCY ERROR: Missing setting FILAMENTCHANGE_YPOS
  #endif
  #if DISABLED(FILAMENTCHANGE_ZADD)
    #error DEPENDENCY ERROR: Missing setting FILAMENTCHANGE_ZADD
  #endif
  #if DISABLED(FILAMENTCHANGE_FIRSTRETRACT)
    #error DEPENDENCY ERROR: Missing setting FILAMENTCHANGE_FIRSTRETRACT
  #endif
  #if DISABLED(FILAMENTCHANGE_FINALRETRACT)
    #error DEPENDENCY ERROR: Missing setting FILAMENTCHANGE_FINALRETRACT
  #endif
  #if DISABLED(FILAMENTCHANGE_PRINTEROFF)
    #error DEPENDENCY ERROR: Missing setting FILAMENTCHANGE_PRINTEROFF
  #endif
#endif
  
//Motion
#if DISABLED(SOFTWARE_MIN_ENDSTOPS)
  #error DEPENDENCY ERROR: Missing setting SOFTWARE_MIN_ENDSTOPS
#endif
#if DISABLED(SOFTWARE_MAX_ENDSTOPS)
  #error DEPENDENCY ERROR: Missing setting SOFTWARE_MAX_ENDSTOPS
#endif
#if ENABLED(AUTO_BED_LEVELING_FEATURE)
  #if ENABLED(AUTO_BED_LEVELING_GRID)
    #if DISABLED(MIN_PROBE_EDGE)
      #error DEPENDENCY ERROR: Missing setting MIN_PROBE_EDGE
    #endif
    #if DISABLED(AUTO_BED_LEVELING_GRID_POINTS)
      #error DEPENDENCY ERROR: Missing setting AUTO_BED_LEVELING_GRID_POINTS
    #endif
  #else
    #if DISABLED(ABL_PROBE_PT_1_X)
      #error DEPENDENCY ERROR: Missing setting ABL_PROBE_PT_1_X
    #endif
    #if DISABLED(ABL_PROBE_PT_1_Y)
      #error DEPENDENCY ERROR: Missing setting ABL_PROBE_PT_1_Y
    #endif
    #if DISABLED(ABL_PROBE_PT_2_X)
      #error DEPENDENCY ERROR: Missing setting ABL_PROBE_PT_2_X
    #endif
    #if DISABLED(ABL_PROBE_PT_2_Y)
      #error DEPENDENCY ERROR: Missing setting ABL_PROBE_PT_2_Y
    #endif
    #if DISABLED(ABL_PROBE_PT_3_X)
      #error DEPENDENCY ERROR: Missing setting ABL_PROBE_PT_3_X
    #endif
    #if DISABLED(ABL_PROBE_PT_3_Y)
      #error DEPENDENCY ERROR: Missing setting ABL_PROBE_PT_3_Y
    #endif
  #endif
  #if DISABLED(X_PROBE_OFFSET_FROM_EXTRUDER)
    #error DEPENDENCY ERROR: Missing setting X_PROBE_OFFSET_FROM_EXTRUDER
  #endif
  #if DISABLED(Y_PROBE_OFFSET_FROM_EXTRUDER)
    #error DEPENDENCY ERROR: Missing setting Y_PROBE_OFFSET_FROM_EXTRUDER
  #endif
  #if DISABLED(Z_PROBE_OFFSET_FROM_EXTRUDER)
    #error DEPENDENCY ERROR: Missing setting Z_PROBE_OFFSET_FROM_EXTRUDER
  #endif
  #if DISABLED(Z_RAISE_BEFORE_HOMING)
    #error DEPENDENCY ERROR: Missing setting Z_RAISE_BEFORE_HOMING
  #endif
  #if DISABLED(Z_RAISE_BEFORE_PROBING)
    #error DEPENDENCY ERROR: Missing setting Z_RAISE_BEFORE_PROBING
  #endif
  #if DISABLED(Z_RAISE_BETWEEN_PROBINGS)
    #error DEPENDENCY ERROR: Missing setting Z_RAISE_BETWEEN_PROBINGS
  #endif
  #if DISABLED(Z_RAISE_AFTER_PROBING)
    #error DEPENDENCY ERROR: Missing setting Z_RAISE_AFTER_PROBING
  #endif
  #if ENABLED(Z_PROBE_SLED)
    #if DISABLED(SLED_DOCKING_OFFSET)
      #error DEPENDENCY ERROR: Missing setting SLED_DOCKING_OFFSET
    #endif
  #endif
  #if ENABLED(Z_SAFE_HOMING)
    #if DISABLED(Z_SAFE_HOMING_X_POINT)
      #error DEPENDENCY ERROR: Missing setting Z_SAFE_HOMING_X_POINT
    #endif
    #if DISABLED(Z_SAFE_HOMING_Y_POINT)
      #error DEPENDENCY ERROR: Missing setting Z_SAFE_HOMING_Y_POINT
    #endif
  #endif
#endif

#if DISABLED(NUM_SERVOS)
  #error DEPENDENCY ERROR: Missing setting NUM_SERVOS 0
#endif
#if NUM_SERVOS > 0
  #if DISABLED(X_ENDSTOP_SERVO_NR)
    #error DEPENDENCY ERROR: Missing setting X_ENDSTOP_SERVO_NR
  #endif
  #if DISABLED(Y_ENDSTOP_SERVO_NR)
    #error DEPENDENCY ERROR: Missing setting Y_ENDSTOP_SERVO_NR
  #endif
  #if DISABLED(Z_ENDSTOP_SERVO_NR)
    #error DEPENDENCY ERROR: Missing setting Z_ENDSTOP_SERVO_NR
  #endif
  #if DISABLED(X_ENDSTOP_SERVO_ANGLES)
    #error DEPENDENCY ERROR: Missing setting X_ENDSTOP_SERVO_ANGLES
  #endif
  #if DISABLED(Y_ENDSTOP_SERVO_ANGLES)
    #error DEPENDENCY ERROR: Missing setting Y_ENDSTOP_SERVO_ANGLES
  #endif
  #if DISABLED(Z_ENDSTOP_SERVO_ANGLES)
    #error DEPENDENCY ERROR: Missing setting Z_ENDSTOP_SERVO_ANGLES
  #endif
  #if DISABLED(SERVO_DEACTIVATION_DELAY)
    #error DEPENDENCY ERROR: Missing setting SERVO_DEACTIVATION_DELAY
  #endif
#endif
#if ENABLED(BABYSTEPPING)
  #if DISABLED(BABYSTEP_INVERT_Z)
    #error DEPENDENCY ERROR: Missing setting BABYSTEP_INVERT_Z
  #endif
  #if DISABLED(BABYSTEP_Z_MULTIPLICATOR)
    #error DEPENDENCY ERROR: Missing setting BABYSTEP_Z_MULTIPLICATOR
  #endif
#endif
#if ENABLED(FWRETRACT)
  #if DISABLED(MIN_RETRACT)
    #error DEPENDENCY ERROR: Missing setting MIN_RETRACT
  #endif
  #if DISABLED(RETRACT_LENGTH)
    #error DEPENDENCY ERROR: Missing setting RETRACT_LENGTH
  #endif
  #if DISABLED(RETRACT_LENGTH_SWAP)
    #error DEPENDENCY ERROR: Missing setting RETRACT_LENGTH_SWAP
  #endif
  #if DISABLED(RETRACT_FEEDRATE)
    #error DEPENDENCY ERROR: Missing setting RETRACT_FEEDRATE
  #endif
  #if DISABLED(RETRACT_ZLIFT)
    #error DEPENDENCY ERROR: Missing setting RETRACT_ZLIFT
  #endif
  #if DISABLED(RETRACT_RECOVER_LENGTH)
    #error DEPENDENCY ERROR: Missing setting RETRACT_RECOVER_LENGTH
  #endif
  #if DISABLED(RETRACT_RECOVER_LENGTH_SWAP)
    #error DEPENDENCY ERROR: Missing setting RETRACT_RECOVER_LENGTH_SWAP
  #endif
  #if DISABLED(RETRACT_RECOVER_FEEDRATE)
    #error DEPENDENCY ERROR: Missing setting RETRACT_RECOVER_FEEDRATE
  #endif
#endif
#if ENABLED(DUAL_X_CARRIAGE)
  #if DISABLED(X2_MIN_POS)
    #error DEPENDENCY ERROR: Missing setting X2_MIN_POS
  #endif
  #if DISABLED(X2_MAX_POS)
    #error DEPENDENCY ERROR: Missing setting X2_MAX_POS
  #endif
  #if DISABLED(X2_HOME_DIR)
    #error DEPENDENCY ERROR: Missing setting X2_HOME_DIR
  #endif
  #if DISABLED(X2_HOME_POS)
    #error DEPENDENCY ERROR: Missing setting X2_HOME_POS
  #endif
  #if DISABLED(DEFAULT_DUAL_X_CARRIAGE_MODE)
    #error DEPENDENCY ERROR: Missing setting DEFAULT_DUAL_X_CARRIAGE_MODE
  #endif
  #if DISABLED(TOOLCHANGE_PARK_ZLIFT)
    #error DEPENDENCY ERROR: Missing setting TOOLCHANGE_PARK_ZLIFT
  #endif
  #if DISABLED(TOOLCHANGE_UNPARK_ZLIFT)
    #error DEPENDENCY ERROR: Missing setting TOOLCHANGE_UNPARK_ZLIFT
  #endif
  #if DISABLED(DEFAULT_DUPLICATION_X_OFFSET)
    #error DEPENDENCY ERROR: Missing setting DEFAULT_DUPLICATION_X_OFFSET
  #endif
#endif
#if ENABLED(Y_DUAL_STEPPER_DRIVERS)
  #if DISABLED(INVERT_Y2_VS_Y_DIR)
    #error DEPENDENCY ERROR: Missing setting INVERT_Y2_VS_Y_DIR
  #endif
#endif

//sensors
#if ENABLED(FILAMENT_SENSOR)
  #if DISABLED(FILAMENT_SENSOR_EXTRUDER_NUM)
    #error DEPENDENCY ERROR: Missing setting FILAMENT_SENSOR_EXTRUDER_NUM
  #endif
  #if DISABLED(MEASUREMENT_DELAY_CM)
    #error DEPENDENCY ERROR: Missing setting MEASUREMENT_DELAY_CM
  #endif
  #if DISABLED(DEFAULT_NOMINAL_FILAMENT_DIA)
    #error DEPENDENCY ERROR: Missing setting DEFAULT_NOMINAL_FILAMENT_DIA 
  #endif
  #if DISABLED(MEASURED_UPPER_LIMIT)
    #error DEPENDENCY ERROR: Missing setting MEASURED_UPPER_LIMIT
  #endif
  #if DISABLED(MEASURED_LOWER_LIMIT)
    #error DEPENDENCY ERROR: Missing setting MEASURED_LOWER_LIMIT
  #endif
  #if DISABLED(MAX_MEASUREMENT_DELAY)
    #error DEPENDENCY ERROR: Missing setting MAX_MEASUREMENT_DELAY
  #endif
  #if DISABLED(DEFAULT_MEASURED_FILAMENT_DIA)
    #error DEPENDENCY ERROR: Missing setting DEFAULT_MEASURED_FILAMENT_DIA
  #endif
#endif
#if ENABLED(FILAMENT_RUNOUT_SENSOR)
  #if DISABLED(FILRUNOUT_PIN_INVERTING)
    #error DEPENDENCY ERROR: Missing setting FILRUNOUT_PIN_INVERTING
  #endif
  #if DISABLED(ENDSTOPPULLUP_FIL_RUNOUT)
    #error DEPENDENCY ERROR: Missing setting ENDSTOPPULLUP_FIL_RUNOUT
  #endif
  #if DISABLED(FILAMENT_RUNOUT_SCRIPT)
    #error DEPENDENCY ERROR: Missing setting FILAMENT_RUNOUT_SCRIPT 
  #endif
#endif
#if ENABLED(POWER_CONSUMPTION)
  #if DISABLED(POWER_VOLTAGE)
    #error DEPENDENCY ERROR: Missing setting POWER_VOLTAGE
  #endif
  #if DISABLED(POWER_SENSITIVITY)
    #error DEPENDENCY ERROR: Missing setting POWER_SENSITIVITY
  #endif
  #if DISABLED(POWER_OFFSET)
    #error DEPENDENCY ERROR: Missing setting POWER_OFFSET 
  #endif
  #if DISABLED(POWER_ZERO)
    #error DEPENDENCY ERROR: Missing setting POWER_ZERO 
  #endif
  #if DISABLED(POWER_ERROR)
    #error DEPENDENCY ERROR: Missing setting POWER_ERROR 
  #endif
  #if DISABLED(POWER_EFFICIENCY)
    #error DEPENDENCY ERROR: Missing setting POWER_EFFICIENCY 
  #endif
#endif

//addon
#if ENABLED(SDSUPPORT)
  #if DISABLED(SD_FINISHED_STEPPERRELEASE)
    #error DEPENDENCY ERROR: Missing setting SD_FINISHED_STEPPERRELEASE
  #endif
  #if DISABLED(SD_FINISHED_RELEASECOMMAND)
    #error DEPENDENCY ERROR: Missing setting SD_FINISHED_RELEASECOMMAND
  #endif
  #if ENABLED(SD_SETTINGS)
    #if DISABLED(SD_CFG_SECONDS)
      #error DEPENDENCY ERROR: Missing setting SD_CFG_SECONDS
    #endif
    #if DISABLED(CFG_SD_FILE)
      #error DEPENDENCY ERROR: Missing setting CFG_SD_FILE
    #endif
    #if DISABLED(CFG_SD_MAX_KEY_LEN)
      #error DEPENDENCY ERROR: Missing setting CFG_SD_MAX_KEY_LEN
    #endif
    #if DISABLED(CFG_SD_MAX_VALUE_LEN)
      #error DEPENDENCY ERROR: Missing setting CFG_SD_MAX_VALUE_LEN
    #endif
  #endif
#endif
#if DISABLED(DISPLAY_CHARSET_HD44780_JAPAN) && DISABLED(DISPLAY_CHARSET_HD44780_WESTERN) && DISABLED(DISPLAY_CHARSET_HD44780_CYRILLIC)
  #error DEPENDENCY ERROR: Missing setting DISPLAY_CHARSET_HD44780_JAPAN or DISPLAY_CHARSET_HD44780_WESTERN or DISPLAY_CHARSET_HD44780_CYRILLIC
#endif
#if ENABLED(SHOW_BOOTSCREEN)
  #if DISABLED(STRING_SPLASH_LINE1)
    #error DEPENDENCY ERROR: Missing setting STRING_SPLASH_LINE1
  #endif
  #if DISABLED(SPLASH_SCREEN_DURATION)
    #error DEPENDENCY ERROR: Missing setting SPLASH_SCREEN_DURATION
  #endif
#endif
#if ENABLED(ENCODER_RATE_MULTIPLIER)
  #if DISABLED(ENCODER_10X_STEPS_PER_SEC)
    #error DEPENDENCY ERROR: Missing setting ENCODER_10X_STEPS_PER_SEC
  #endif
  #if DISABLED(ENCODER_100X_STEPS_PER_SEC)
    #error DEPENDENCY ERROR: Missing setting ENCODER_100X_STEPS_PER_SEC
  #endif
#endif
#if MB(ALLIGATOR)
  #if DISABLED(UI_VOLTAGE_LEVEL)
    #error DEPENDENCY ERROR: Missing setting UI_VOLTAGE_LEVEL
  #endif
#endif
#if ENABLED(REPRAPWORLD_KEYPAD)
  #if DISABLED(REPRAPWORLD_KEYPAD_MOVE_STEP)
    #error DEPENDENCY ERROR: Missing setting REPRAPWORLD_KEYPAD_MOVE_STEP
  #endif
#endif
#if ENABLED(LCD_PROGRESS_BAR)
  #if DISABLED(PROGRESS_BAR_BAR_TIME)
    #error DEPENDENCY ERROR: Missing setting PROGRESS_BAR_BAR_TIME
  #endif
  #if DISABLED(PROGRESS_BAR_MSG_TIME)
    #error DEPENDENCY ERROR: Missing setting PROGRESS_BAR_MSG_TIME
  #endif
  #if DISABLED(PROGRESS_MSG_EXPIRE)
    #error DEPENDENCY ERROR: Missing setting PROGRESS_MSG_EXPIRE
  #endif
#endif
#if ENABLED(CHDK)
  #if DISABLED(CHDK_DELAY)
    #error DEPENDENCY ERROR: Missing setting CHDK_DELAY
  #endif
#endif
//adv motion
#if ENABLED(DIGIPOT_I2C)
  #if DISABLED(DIGIPOT_I2C_NUM_CHANNELS)
    #error DEPENDENCY ERROR: Missing setting DIGIPOT_I2C_NUM_CHANNELS
  #endif
  #if DISABLED(DIGIPOT_I2C_MOTOR_CURRENTS)
    #error DEPENDENCY ERROR: Missing setting DIGIPOT_I2C_MOTOR_CURRENTS
  #endif
#endif
#if ENABLED(HAVE_TMCDRIVER)
  #if ENABLED(X_IS_TMC)
    #if DISABLED(X_MAX_CURRENT)
      #error DEPENDENCY ERROR: Missing setting X_MAX_CURRENT
    #endif
    #if DISABLED(X_SENSE_RESISTOR)
      #error DEPENDENCY ERROR: Missing setting X_SENSE_RESISTOR
    #endif
    #if DISABLED(X_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting X_MICROSTEPS
    #endif
  #endif
  #if ENABLED(X2_IS_TMC)
    #if DISABLED(X2_MAX_CURRENT)
      #error DEPENDENCY ERROR: Missing setting X2_MAX_CURRENT
    #endif
    #if DISABLED(X2_SENSE_RESISTOR)
      #error DEPENDENCY ERROR: Missing setting X2_SENSE_RESISTOR
    #endif
    #if DISABLED(X2_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting X2_MICROSTEPS
    #endif
  #endif
  #if ENABLED(Y_IS_TMC)
    #if DISABLED(Y_MAX_CURRENT)
      #error DEPENDENCY ERROR: Missing setting Y_MAX_CURRENT
    #endif
    #if DISABLED(Y_SENSE_RESISTOR)
      #error DEPENDENCY ERROR: Missing setting Y_SENSE_RESISTOR
    #endif
    #if DISABLED(Y_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting Y_MICROSTEPS
    #endif
  #endif
  #if ENABLED(Y2_IS_TMC)
    #if DISABLED(Y2_MAX_CURRENT)
      #error DEPENDENCY ERROR: Missing setting Y2_MAX_CURRENT
    #endif
    #if DISABLED(Y2_SENSE_RESISTOR)
      #error DEPENDENCY ERROR: Missing setting Y2_SENSE_RESISTOR
    #endif
    #if DISABLED(Y2_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting Y2_MICROSTEPS
    #endif
  #endif
  #if ENABLED(Z_IS_TMC)
    #if DISABLED(Z_MAX_CURRENT)
      #error DEPENDENCY ERROR: Missing setting Z_MAX_CURRENT
    #endif
    #if DISABLED(Z_SENSE_RESISTOR)
      #error DEPENDENCY ERROR: Missing setting Z_SENSE_RESISTOR
    #endif
    #if DISABLED(Z_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting Z_MICROSTEPS
    #endif
  #endif
  #if ENABLED(Z2_IS_TMC)
    #if DISABLED(Z2_MAX_CURRENT)
      #error DEPENDENCY ERROR: Missing setting Z2_MAX_CURRENT
    #endif
    #if DISABLED(Z2_SENSE_RESISTOR)
      #error DEPENDENCY ERROR: Missing setting Z2_SENSE_RESISTOR
    #endif
    #if DISABLED(Z2_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting Z2_MICROSTEPS
    #endif
  #endif
  #if ENABLED(E0_IS_TMC)
    #if DISABLED(E0_MAX_CURRENT)
      #error DEPENDENCY ERROR: Missing setting E0_MAX_CURRENT
    #endif
    #if DISABLED(E0_SENSE_RESISTOR)
      #error DEPENDENCY ERROR: Missing setting E0_SENSE_RESISTOR
    #endif
    #if DISABLED(E0_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting E0_MICROSTEPS
    #endif
  #endif
  #if ENABLED(E1_IS_TMC)
    #if DISABLED(E1_MAX_CURRENT)
      #error DEPENDENCY ERROR: Missing setting E1_MAX_CURRENT
    #endif
    #if DISABLED(E1_SENSE_RESISTOR)
      #error DEPENDENCY ERROR: Missing setting E1_SENSE_RESISTOR
    #endif
    #if DISABLED(E1_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting E1_MICROSTEPS
    #endif
  #endif
  #if ENABLED(E2_IS_TMC)
    #if DISABLED(E2_MAX_CURRENT)
      #error DEPENDENCY ERROR: Missing setting E2_MAX_CURRENT
    #endif
    #if DISABLED(E2_SENSE_RESISTOR)
      #error DEPENDENCY ERROR: Missing setting E2_SENSE_RESISTOR
    #endif
    #if DISABLED(E2_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting E2_MICROSTEPS
    #endif
  #endif
  #if ENABLED(E3_IS_TMC)
    #if DISABLED(E3_MAX_CURRENT)
      #error DEPENDENCY ERROR: Missing setting E3_MAX_CURRENT
    #endif
    #if DISABLED(E3_SENSE_RESISTOR)
      #error DEPENDENCY ERROR: Missing setting E3_SENSE_RESISTOR
    #endif
    #if DISABLED(E3_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting E3_MICROSTEPS
    #endif
  #endif
#endif
#if ENABLED(HAVE_L6470DRIVER)
  #if ENABLED(X_IS_L6470)
    #if DISABLED(X_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting X_MICROSTEPS
    #endif
    #if DISABLED(X_K_VAL)
      #error DEPENDENCY ERROR: Missing setting X_K_VAL
    #endif
    #if DISABLED(X_OVERCURRENT)
      #error DEPENDENCY ERROR: Missing setting X_OVERCURRENT
    #endif
    #if DISABLED(X_STALLCURRENT)
      #error DEPENDENCY ERROR: Missing setting X_STALLCURRENT
    #endif
  #endif
  #if ENABLED(X2_IS_L6470)
    #if DISABLED(X2_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting X2_MICROSTEPS
    #endif
    #if DISABLED(X2_K_VAL)
      #error DEPENDENCY ERROR: Missing setting X2_K_VAL
    #endif
    #if DISABLED(X2_OVERCURRENT)
      #error DEPENDENCY ERROR: Missing setting X2_OVERCURRENT
    #endif
    #if DISABLED(X2_STALLCURRENT)
      #error DEPENDENCY ERROR: Missing setting X2_STALLCURRENT
    #endif
  #endif
  #if ENABLED(Y_IS_L6470)
    #if DISABLED(Y_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting Y_MICROSTEPS
    #endif
    #if DISABLED(Y_K_VAL)
      #error DEPENDENCY ERROR: Missing setting Y_K_VAL
    #endif
    #if DISABLED(Y_OVERCURRENT)
      #error DEPENDENCY ERROR: Missing setting Y_OVERCURRENT
    #endif
    #if DISABLED(Y_STALLCURRENT)
      #error DEPENDENCY ERROR: Missing setting Y_STALLCURRENT
    #endif
  #endif
  #if ENABLED(Y2_IS_L6470)
    #if DISABLED(Y2_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting Y2_MICROSTEPS
    #endif
    #if DISABLED(Y2_K_VAL)
      #error DEPENDENCY ERROR: Missing setting Y2_K_VAL
    #endif
    #if DISABLED(Y2_OVERCURRENT)
      #error DEPENDENCY ERROR: Missing setting Y2_OVERCURRENT
    #endif
    #if DISABLED(Y2_STALLCURRENT)
      #error DEPENDENCY ERROR: Missing setting Y2_STALLCURRENT
    #endif
  #endif
  #if ENABLED(Z_IS_L6470)
    #if DISABLED(Z_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting Z_MICROSTEPS
    #endif
    #if DISABLED(Z_K_VAL)
      #error DEPENDENCY ERROR: Missing setting Z_K_VAL
    #endif
    #if DISABLED(Z_OVERCURRENT)
      #error DEPENDENCY ERROR: Missing setting Z_OVERCURRENT
    #endif
    #if DISABLED(Z_STALLCURRENT)
      #error DEPENDENCY ERROR: Missing setting Z_STALLCURRENT
    #endif
  #endif
  #if ENABLED(Z2_IS_L6470)
    #if DISABLED(Z2_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting Z2_MICROSTEPS
    #endif
    #if DISABLED(Z2_K_VAL)
      #error DEPENDENCY ERROR: Missing setting Z2_K_VAL
    #endif
    #if DISABLED(Z2_OVERCURRENT)
      #error DEPENDENCY ERROR: Missing setting Z2_OVERCURRENT
    #endif
    #if DISABLED(Z2_STALLCURRENT)
      #error DEPENDENCY ERROR: Missing setting Z2_STALLCURRENT
    #endif
  #endif
  #if ENABLED(E0_IS_L6470)
    #if DISABLED(E0_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting E0_MICROSTEPS
    #endif
    #if DISABLED(E0_K_VAL)
      #error DEPENDENCY ERROR: Missing setting E0_K_VAL
    #endif
    #if DISABLED(E0_OVERCURRENT)
      #error DEPENDENCY ERROR: Missing setting E0_OVERCURRENT
    #endif
    #if DISABLED(E0_STALLCURRENT)
      #error DEPENDENCY ERROR: Missing setting E0_STALLCURRENT
    #endif
  #endif
  #if ENABLED(E1_IS_L6470)
    #if DISABLED(E1_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting E1_MICROSTEPS
    #endif
    #if DISABLED(E1_K_VAL)
      #error DEPENDENCY ERROR: Missing setting E1_K_VAL
    #endif
    #if DISABLED(E1_OVERCURRENT)
      #error DEPENDENCY ERROR: Missing setting E1_OVERCURRENT
    #endif
    #if DISABLED(E1_STALLCURRENT)
      #error DEPENDENCY ERROR: Missing setting E1_STALLCURRENT
    #endif
  #endif
  #if ENABLED(E2_IS_L6470)
    #if DISABLED(E2_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting E2_MICROSTEPS
    #endif
    #if DISABLED(E2_K_VAL)
      #error DEPENDENCY ERROR: Missing setting E2_K_VAL
    #endif
    #if DISABLED(E2_OVERCURRENT)
      #error DEPENDENCY ERROR: Missing setting E2_OVERCURRENT
    #endif
    #if DISABLED(E2_STALLCURRENT)
      #error DEPENDENCY ERROR: Missing setting E2_STALLCURRENT
    #endif
  #endif
  #if ENABLED(E3_IS_L6470)
    #if DISABLED(E3_MICROSTEPS)
      #error DEPENDENCY ERROR: Missing setting E3_MICROSTEPS
    #endif
    #if DISABLED(E3_K_VAL)
      #error DEPENDENCY ERROR: Missing setting E3_K_VAL
    #endif
    #if DISABLED(E3_OVERCURRENT)
      #error DEPENDENCY ERROR: Missing setting E3_OVERCURRENT
    #endif
    #if DISABLED(E3_STALLCURRENT)
      #error DEPENDENCY ERROR: Missing setting E3_STALLCURRENT
    #endif
  #endif
#endif
//buffer
#if DISABLED(BLOCK_BUFFER_SIZE)
  #error DEPENDENCY ERROR: Missing setting BLOCK_BUFFER_SIZE
#endif
#if DISABLED(MAX_CMD_SIZE)
  #error DEPENDENCY ERROR: Missing setting MAX_CMD_SIZE
#endif
#if DISABLED(BUFSIZE)
  #error DEPENDENCY ERROR: Missing setting BUFSIZE
#endif
#if DISABLED(NUM_POSITON_SLOTS)
  #error DEPENDENCY ERROR: Missing setting NUM_POSITON_SLOTS
#endif
#if DISABLED(DROP_SEGMENTS)
  #error DEPENDENCY ERROR: Missing setting DROP_SEGMENTS
#endif
#if DISABLED(DROP_SEGMENTS)
  #error DEPENDENCY ERROR: Missing setting DROP_SEGMENTS
#endif
#if DISABLED(DEFAULT_MINSEGMENTTIME)
  #error DEPENDENCY ERROR: Missing setting DEFAULT_MINSEGMENTTIME
#endif
#if DISABLED(MM_PER_ARC_SEGMENT)
  #error DEPENDENCY ERROR: Missing setting MM_PER_ARC_SEGMENT
#endif
#if DISABLED(N_ARC_CORRECTION)
  #error DEPENDENCY ERROR: Missing setting N_ARC_CORRECTION
#endif

#endif